# Both testing stages depend on the build stage. By using the "needs"
# keyword, we prevent the testing stages from blocking, in favor of a
# DAG.
stages:
  - build
  - test-unit
  - test-integ

# Rules to determine when a pipeline will be generated. If none of these rules
# match, no pipeline will be generated.
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"'
    - if: '$CI_PIPELINE_SOURCE == "external_pull_request_event" && $CI_EXTERNAL_PULL_REQUEST_TARGET_BRANCH_NAME == "dev"'
    - if: '$CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "dev"'

##### System Templates #####

# Generic system templates used to contruct the final jobs on specific
# systems within their respective <system>.yml file. Currently
# these are LLNL specific, but can be adjusted or added to as new
# systems become available.
#
# The NNODES, WALL_TIME, and STORAGE_SIZE variables can be altered in
# Gitlab interface if/when the defaults need to be changed.

.base-template:
  retry:
    max: 1
    when:
      - unknown_failure
      - stuck_or_timeout_failure

.slurm-single-node-template:
  variables:
    LLNL_SLURM_SCHEDULER_PARAMETERS: "-N 1 -p pbatch -t $UNIT_WALL_TIME -J unifyfs-unit-tests"

.slurm-multi-node-template:
  variables:
    LLNL_SLURM_SCHEDULER_PARAMETERS: "-N $NNODES -p pbatch -t $INTEG_WALL_TIME -J unifyfs-integ-tests"

.lsf-single-node-template:
  variables:
    LLNL_LSF_SCHEDULER_PARAMETERS: "-nnodes 1 -q pbatch -W $UNIT_WALL_TIME -J unifyfs-unit-tests"

.lsf-multi-node-template:
  variables:
    LLNL_LSF_SCHEDULER_PARAMETERS: "-nnodes $NNODES -stage storage=${STORAGE_SIZE} -q pbatch -W $INTEG_WALL_TIME -J unifyfs-integ-tests"

##### Job Templates #####

# Build script used by each system. The CC and FC variables are set in
# the specific job scripts and evaluated in the before_script in order
# to customize which compiler will be used for each job.
# An artifact is created to pass on to the testing stages. The
# test-unit stage requires the unifyfs-build/ files and the test-integ
# stage requires the unifyfs-install/ files.
.build-template:
  stage: build
  script:
    - ./autogen.sh
    - mkdir -p unifyfs-build unifyfs-install && cd unifyfs-build
    - ../configure CC=$CC_PATH FC=$FC_PATH --prefix=$CI_PROJECT_DIR/unifyfs-install --enable-fortran --disable-silent-rules
    - make V=1
    - make V=1 install
  needs: []
  artifacts:
    name: "${CI_JOB_NAME}-${CI_PIPELINE_ID}"
    untracked: true
    expire_in: 1 hour
    paths:
      - unifyfs-build/
      - unifyfs-install/

.unit-test-template:
  stage: test-unit
  script:
    - cd unifyfs-build/t && make check
  after_script:
    - rm -rf /tmp/unify* /tmp/tmp.* /tmp/mdhim* /tmp/na_sm | true

# Variables here are used for the integration test suite and can be
# adjusted in the Gitlab interface. See our testing documentation for
# full details.
.integ-test-template:
  stage: test-integ
  variables:
    UNIFYFS_INSTALL: "$CI_PROJECT_DIR/unifyfs-install"
    CI_PROJDIR: "$CI_PROJECT_DIR"
    CI_NPROCS: "$NPROCS"
  script:
    - cd t/ci && prove -v RUN_CI_TESTS.sh

##### Jobs #####

# Since Gitlab currently runs in the user's home environment, the
# before_script is currently only set up to load the proper Spack
# modules, if they are available, to prevent changing the user's
# environment. Install any needed modules in the user's environment
# prior to running when new compilers or architectures need to be
# tested.
#
# The COMPILER, CC_PATH, and FC_PATH variables are evaluated here. Set
# them in their specific job scripts.
# SPACK_COMPILER and SPACK_ARCH are then set to load the matching
# dependencies for the desired compiler.
before_script:
  - which spack || ((cd $HOME/spack && git describe) && . $HOME/spack/share/spack/setup-env.sh)
  - module load $COMPILER
  - CC_PATH=$($CC_COMMAND)
  - FC_PATH=$($FC_COMMAND)
  - SPACK_COMPILER=${COMPILER//\//@}
  - SPACK_ARCH="$(spack arch -p)-$(spack arch -o)-$(uname -m)"
  - spack load flatcc %$SPACK_COMPILER arch=$SPACK_ARCH
  - spack load gotcha %$SPACK_COMPILER arch=$SPACK_ARCH
  - spack load leveldb %$SPACK_COMPILER arch=$SPACK_ARCH
  - spack load argobots %$SPACK_COMPILER arch=$SPACK_ARCH
  - spack load mercury %$SPACK_COMPILER arch=$SPACK_ARCH
  - spack load margo %$SPACK_COMPILER arch=$SPACK_ARCH
  - spack load spath %$SPACK_COMPILER arch=$SPACK_ARCH

# System specific jobs
include:
  - local: .gitlab/catalyst.yml
  - local: .gitlab/lassen.yml
